= Auto trade

== Develop

[source,shell]
----
yarn
yarn develop-start
yarn lint-fix
yarn qa
yarn develop-stop
----

== Features

[%hardbreaks]
  Contract: AutoTrade
    1.1 Any User can top up the contract for any amount
      ✓ Balance: amount must be more zero (86ms)
      ✓ Balance: updated (96ms)
    1.2 Any User can create offer to convert into stablecoin
      ✓ Offer: need amounts more zero (42ms)
      ✓ Offer: updated
    1.3 Contract Owner can approve the offer to convert into stablecoin
      ✓ User can not approve (53ms)
      ✓ Owner can approve (61ms)
    1.4 Contract Owner can approve the offer to convert into stablecoin with a reduction of the amount
      ✓ Owner can approve with a reduction (69ms)
    1.5 Contract Owner can reject the offer to convert into stablecoin
      ✓ User can not reject
      ✓ Owner can reject (69ms)
    1.6 The User can accept the offer
      ✓ 1.6 The User can accept the offer (80ms)
    1.7 Requesting User can reject the offer
      ✓ Requesting User reject (61ms)
    TODO 1.8 The User can delegate the offer to another person in the off-chain
      ✓ TODO Open the payment channel
      ✓ TODO Signs messages
      ✓ TODO Closes the payment channel

[plantuml, "flow confirmation pending orders", svg, width=640, align=center]
----
skinparam shadowing false

state Offer {
  Finished ---> Proposed

  Proposed ---> Rejected
  Proposed ---> Accepted
  Proposed ---> Approved

  Accepted ---> Approved
  Accepted ---> Rejected

  Approved ---> Rejected
  Rejected ---> Finished
  Approved ---> Finished
}
----
